apiVersion: apps/v1
kind: Deployment

metadata:
  name: customer-segmentation-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: customer-segmentation

  template:
    metadata:
      labels:
        app: customer-segmentation

    spec:
      containers:
        - name: customer-segmentation
          image: customer-segmentation:latest

          ports:
            - containerPort: 8501